// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_2eproto;
class Header;
struct HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class MultiModalInput;
struct MultiModalInputDefaultTypeInternal;
extern MultiModalInputDefaultTypeInternal _MultiModalInput_default_instance_;
class Tensor;
struct TensorDefaultTypeInternal;
extern TensorDefaultTypeInternal _Tensor_default_instance_;
class Time;
struct TimeDefaultTypeInternal;
extern TimeDefaultTypeInternal _Time_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Header* Arena::CreateMaybeMessage<::Header>(Arena*);
template<> ::MultiModalInput* Arena::CreateMaybeMessage<::MultiModalInput>(Arena*);
template<> ::Tensor* Arena::CreateMaybeMessage<::Tensor>(Arena*);
template<> ::Time* Arena::CreateMaybeMessage<::Time>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum Tensor_DataType : int {
  Tensor_DataType_FLOAT64 = 0,
  Tensor_DataType_UINT8 = 1,
  Tensor_DataType_STRING = 2,
  Tensor_DataType_FLOAT32 = 3,
  Tensor_DataType_INT32 = 4,
  Tensor_DataType_FP16 = 5,
  Tensor_DataType_Tensor_DataType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Tensor_DataType_Tensor_DataType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Tensor_DataType_IsValid(int value);
constexpr Tensor_DataType Tensor_DataType_DataType_MIN = Tensor_DataType_FLOAT64;
constexpr Tensor_DataType Tensor_DataType_DataType_MAX = Tensor_DataType_FP16;
constexpr int Tensor_DataType_DataType_ARRAYSIZE = Tensor_DataType_DataType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Tensor_DataType_descriptor();
template<typename T>
inline const std::string& Tensor_DataType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Tensor_DataType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Tensor_DataType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Tensor_DataType_descriptor(), enum_t_value);
}
inline bool Tensor_DataType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Tensor_DataType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Tensor_DataType>(
    Tensor_DataType_descriptor(), name, value);
}
// ===================================================================

class Time final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Time) */ {
 public:
  inline Time() : Time(nullptr) {}
  ~Time() override;
  explicit PROTOBUF_CONSTEXPR Time(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Time(const Time& from);
  Time(Time&& from) noexcept
    : Time() {
    *this = ::std::move(from);
  }

  inline Time& operator=(const Time& from) {
    CopyFrom(from);
    return *this;
  }
  inline Time& operator=(Time&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Time& default_instance() {
    return *internal_default_instance();
  }
  static inline const Time* internal_default_instance() {
    return reinterpret_cast<const Time*>(
               &_Time_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Time& a, Time& b) {
    a.Swap(&b);
  }
  inline void Swap(Time* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Time* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Time* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Time>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Time& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Time& from) {
    Time::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Time* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Time";
  }
  protected:
  explicit Time(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSecFieldNumber = 1,
    kNsecFieldNumber = 2,
  };
  // int64 sec = 1;
  void clear_sec();
  int64_t sec() const;
  void set_sec(int64_t value);
  private:
  int64_t _internal_sec() const;
  void _internal_set_sec(int64_t value);
  public:

  // int32 nsec = 2;
  void clear_nsec();
  int32_t nsec() const;
  void set_nsec(int32_t value);
  private:
  int32_t _internal_nsec() const;
  void _internal_set_nsec(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Time)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t sec_;
    int32_t nsec_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class Header final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Header) */ {
 public:
  inline Header() : Header(nullptr) {}
  ~Header() override;
  explicit PROTOBUF_CONSTEXPR Header(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Header(const Header& from);
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  inline Header& operator=(Header&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Header& default_instance() {
    return *internal_default_instance();
  }
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }
  inline void Swap(Header* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Header* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Header* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Header>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Header& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Header& from) {
    Header::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Header* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Header";
  }
  protected:
  explicit Header(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameIdFieldNumber = 3,
    kStampFieldNumber = 2,
    kSeqFieldNumber = 1,
    kTypeFieldNumber = 4,
    kResetFieldNumber = 5,
  };
  // string frame_id = 3;
  void clear_frame_id();
  const std::string& frame_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_frame_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_frame_id();
  PROTOBUF_NODISCARD std::string* release_frame_id();
  void set_allocated_frame_id(std::string* frame_id);
  private:
  const std::string& _internal_frame_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_frame_id(const std::string& value);
  std::string* _internal_mutable_frame_id();
  public:

  // .Time stamp = 2;
  bool has_stamp() const;
  private:
  bool _internal_has_stamp() const;
  public:
  void clear_stamp();
  const ::Time& stamp() const;
  PROTOBUF_NODISCARD ::Time* release_stamp();
  ::Time* mutable_stamp();
  void set_allocated_stamp(::Time* stamp);
  private:
  const ::Time& _internal_stamp() const;
  ::Time* _internal_mutable_stamp();
  public:
  void unsafe_arena_set_allocated_stamp(
      ::Time* stamp);
  ::Time* unsafe_arena_release_stamp();

  // uint32 seq = 1;
  void clear_seq();
  uint32_t seq() const;
  void set_seq(uint32_t value);
  private:
  uint32_t _internal_seq() const;
  void _internal_set_seq(uint32_t value);
  public:

  // uint32 type = 4;
  void clear_type();
  uint32_t type() const;
  void set_type(uint32_t value);
  private:
  uint32_t _internal_type() const;
  void _internal_set_type(uint32_t value);
  public:

  // bool reset = 5;
  void clear_reset();
  bool reset() const;
  void set_reset(bool value);
  private:
  bool _internal_reset() const;
  void _internal_set_reset(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Header)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_id_;
    ::Time* stamp_;
    uint32_t seq_;
    uint32_t type_;
    bool reset_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class Tensor final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Tensor) */ {
 public:
  inline Tensor() : Tensor(nullptr) {}
  ~Tensor() override;
  explicit PROTOBUF_CONSTEXPR Tensor(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Tensor(const Tensor& from);
  Tensor(Tensor&& from) noexcept
    : Tensor() {
    *this = ::std::move(from);
  }

  inline Tensor& operator=(const Tensor& from) {
    CopyFrom(from);
    return *this;
  }
  inline Tensor& operator=(Tensor&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Tensor& default_instance() {
    return *internal_default_instance();
  }
  static inline const Tensor* internal_default_instance() {
    return reinterpret_cast<const Tensor*>(
               &_Tensor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Tensor& a, Tensor& b) {
    a.Swap(&b);
  }
  inline void Swap(Tensor* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Tensor* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Tensor* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Tensor>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Tensor& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Tensor& from) {
    Tensor::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Tensor* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Tensor";
  }
  protected:
  explicit Tensor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Tensor_DataType DataType;
  static constexpr DataType FLOAT64 =
    Tensor_DataType_FLOAT64;
  static constexpr DataType UINT8 =
    Tensor_DataType_UINT8;
  static constexpr DataType STRING =
    Tensor_DataType_STRING;
  static constexpr DataType FLOAT32 =
    Tensor_DataType_FLOAT32;
  static constexpr DataType INT32 =
    Tensor_DataType_INT32;
  static constexpr DataType FP16 =
    Tensor_DataType_FP16;
  static inline bool DataType_IsValid(int value) {
    return Tensor_DataType_IsValid(value);
  }
  static constexpr DataType DataType_MIN =
    Tensor_DataType_DataType_MIN;
  static constexpr DataType DataType_MAX =
    Tensor_DataType_DataType_MAX;
  static constexpr int DataType_ARRAYSIZE =
    Tensor_DataType_DataType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  DataType_descriptor() {
    return Tensor_DataType_descriptor();
  }
  template<typename T>
  static inline const std::string& DataType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, DataType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function DataType_Name.");
    return Tensor_DataType_Name(enum_t_value);
  }
  static inline bool DataType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      DataType* value) {
    return Tensor_DataType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kShapeFieldNumber = 2,
    kDataFieldNumber = 3,
    kDtypeFieldNumber = 1,
  };
  // repeated int32 shape = 2;
  int shape_size() const;
  private:
  int _internal_shape_size() const;
  public:
  void clear_shape();
  private:
  int32_t _internal_shape(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_shape() const;
  void _internal_add_shape(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_shape();
  public:
  int32_t shape(int index) const;
  void set_shape(int index, int32_t value);
  void add_shape(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      shape() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_shape();

  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // .Tensor.DataType dtype = 1;
  void clear_dtype();
  ::Tensor_DataType dtype() const;
  void set_dtype(::Tensor_DataType value);
  private:
  ::Tensor_DataType _internal_dtype() const;
  void _internal_set_dtype(::Tensor_DataType value);
  public:

  // @@protoc_insertion_point(class_scope:Tensor)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > shape_;
    mutable std::atomic<int> _shape_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int dtype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class MultiModalInput final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MultiModalInput) */ {
 public:
  inline MultiModalInput() : MultiModalInput(nullptr) {}
  ~MultiModalInput() override;
  explicit PROTOBUF_CONSTEXPR MultiModalInput(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MultiModalInput(const MultiModalInput& from);
  MultiModalInput(MultiModalInput&& from) noexcept
    : MultiModalInput() {
    *this = ::std::move(from);
  }

  inline MultiModalInput& operator=(const MultiModalInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline MultiModalInput& operator=(MultiModalInput&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MultiModalInput& default_instance() {
    return *internal_default_instance();
  }
  static inline const MultiModalInput* internal_default_instance() {
    return reinterpret_cast<const MultiModalInput*>(
               &_MultiModalInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MultiModalInput& a, MultiModalInput& b) {
    a.Swap(&b);
  }
  inline void Swap(MultiModalInput* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MultiModalInput* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MultiModalInput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MultiModalInput>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MultiModalInput& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MultiModalInput& from) {
    MultiModalInput::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MultiModalInput* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MultiModalInput";
  }
  protected:
  explicit MultiModalInput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImagesFieldNumber = 2,
    kLanguagesFieldNumber = 3,
    kStatesFieldNumber = 4,
    kHeaderFieldNumber = 1,
  };
  // repeated .Tensor images = 2;
  int images_size() const;
  private:
  int _internal_images_size() const;
  public:
  void clear_images();
  ::Tensor* mutable_images(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >*
      mutable_images();
  private:
  const ::Tensor& _internal_images(int index) const;
  ::Tensor* _internal_add_images();
  public:
  const ::Tensor& images(int index) const;
  ::Tensor* add_images();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >&
      images() const;

  // repeated .Tensor languages = 3;
  int languages_size() const;
  private:
  int _internal_languages_size() const;
  public:
  void clear_languages();
  ::Tensor* mutable_languages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >*
      mutable_languages();
  private:
  const ::Tensor& _internal_languages(int index) const;
  ::Tensor* _internal_add_languages();
  public:
  const ::Tensor& languages(int index) const;
  ::Tensor* add_languages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >&
      languages() const;

  // repeated .Tensor states = 4;
  int states_size() const;
  private:
  int _internal_states_size() const;
  public:
  void clear_states();
  ::Tensor* mutable_states(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >*
      mutable_states();
  private:
  const ::Tensor& _internal_states(int index) const;
  ::Tensor* _internal_add_states();
  public:
  const ::Tensor& states(int index) const;
  ::Tensor* add_states();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >&
      states() const;

  // .Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::Header& header() const;
  PROTOBUF_NODISCARD ::Header* release_header();
  ::Header* mutable_header();
  void set_allocated_header(::Header* header);
  private:
  const ::Header& _internal_header() const;
  ::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::Header* header);
  ::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:MultiModalInput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor > images_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor > languages_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor > states_;
    ::Header* header_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Time

// int64 sec = 1;
inline void Time::clear_sec() {
  _impl_.sec_ = int64_t{0};
}
inline int64_t Time::_internal_sec() const {
  return _impl_.sec_;
}
inline int64_t Time::sec() const {
  // @@protoc_insertion_point(field_get:Time.sec)
  return _internal_sec();
}
inline void Time::_internal_set_sec(int64_t value) {
  
  _impl_.sec_ = value;
}
inline void Time::set_sec(int64_t value) {
  _internal_set_sec(value);
  // @@protoc_insertion_point(field_set:Time.sec)
}

// int32 nsec = 2;
inline void Time::clear_nsec() {
  _impl_.nsec_ = 0;
}
inline int32_t Time::_internal_nsec() const {
  return _impl_.nsec_;
}
inline int32_t Time::nsec() const {
  // @@protoc_insertion_point(field_get:Time.nsec)
  return _internal_nsec();
}
inline void Time::_internal_set_nsec(int32_t value) {
  
  _impl_.nsec_ = value;
}
inline void Time::set_nsec(int32_t value) {
  _internal_set_nsec(value);
  // @@protoc_insertion_point(field_set:Time.nsec)
}

// -------------------------------------------------------------------

// Header

// uint32 seq = 1;
inline void Header::clear_seq() {
  _impl_.seq_ = 0u;
}
inline uint32_t Header::_internal_seq() const {
  return _impl_.seq_;
}
inline uint32_t Header::seq() const {
  // @@protoc_insertion_point(field_get:Header.seq)
  return _internal_seq();
}
inline void Header::_internal_set_seq(uint32_t value) {
  
  _impl_.seq_ = value;
}
inline void Header::set_seq(uint32_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:Header.seq)
}

// .Time stamp = 2;
inline bool Header::_internal_has_stamp() const {
  return this != internal_default_instance() && _impl_.stamp_ != nullptr;
}
inline bool Header::has_stamp() const {
  return _internal_has_stamp();
}
inline void Header::clear_stamp() {
  if (GetArenaForAllocation() == nullptr && _impl_.stamp_ != nullptr) {
    delete _impl_.stamp_;
  }
  _impl_.stamp_ = nullptr;
}
inline const ::Time& Header::_internal_stamp() const {
  const ::Time* p = _impl_.stamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::Time&>(
      ::_Time_default_instance_);
}
inline const ::Time& Header::stamp() const {
  // @@protoc_insertion_point(field_get:Header.stamp)
  return _internal_stamp();
}
inline void Header::unsafe_arena_set_allocated_stamp(
    ::Time* stamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stamp_);
  }
  _impl_.stamp_ = stamp;
  if (stamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Header.stamp)
}
inline ::Time* Header::release_stamp() {
  
  ::Time* temp = _impl_.stamp_;
  _impl_.stamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Time* Header::unsafe_arena_release_stamp() {
  // @@protoc_insertion_point(field_release:Header.stamp)
  
  ::Time* temp = _impl_.stamp_;
  _impl_.stamp_ = nullptr;
  return temp;
}
inline ::Time* Header::_internal_mutable_stamp() {
  
  if (_impl_.stamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::Time>(GetArenaForAllocation());
    _impl_.stamp_ = p;
  }
  return _impl_.stamp_;
}
inline ::Time* Header::mutable_stamp() {
  ::Time* _msg = _internal_mutable_stamp();
  // @@protoc_insertion_point(field_mutable:Header.stamp)
  return _msg;
}
inline void Header::set_allocated_stamp(::Time* stamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.stamp_;
  }
  if (stamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(stamp);
    if (message_arena != submessage_arena) {
      stamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stamp, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.stamp_ = stamp;
  // @@protoc_insertion_point(field_set_allocated:Header.stamp)
}

// string frame_id = 3;
inline void Header::clear_frame_id() {
  _impl_.frame_id_.ClearToEmpty();
}
inline const std::string& Header::frame_id() const {
  // @@protoc_insertion_point(field_get:Header.frame_id)
  return _internal_frame_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Header::set_frame_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.frame_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Header.frame_id)
}
inline std::string* Header::mutable_frame_id() {
  std::string* _s = _internal_mutable_frame_id();
  // @@protoc_insertion_point(field_mutable:Header.frame_id)
  return _s;
}
inline const std::string& Header::_internal_frame_id() const {
  return _impl_.frame_id_.Get();
}
inline void Header::_internal_set_frame_id(const std::string& value) {
  
  _impl_.frame_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Header::_internal_mutable_frame_id() {
  
  return _impl_.frame_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Header::release_frame_id() {
  // @@protoc_insertion_point(field_release:Header.frame_id)
  return _impl_.frame_id_.Release();
}
inline void Header::set_allocated_frame_id(std::string* frame_id) {
  if (frame_id != nullptr) {
    
  } else {
    
  }
  _impl_.frame_id_.SetAllocated(frame_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.frame_id_.IsDefault()) {
    _impl_.frame_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Header.frame_id)
}

// uint32 type = 4;
inline void Header::clear_type() {
  _impl_.type_ = 0u;
}
inline uint32_t Header::_internal_type() const {
  return _impl_.type_;
}
inline uint32_t Header::type() const {
  // @@protoc_insertion_point(field_get:Header.type)
  return _internal_type();
}
inline void Header::_internal_set_type(uint32_t value) {
  
  _impl_.type_ = value;
}
inline void Header::set_type(uint32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Header.type)
}

// bool reset = 5;
inline void Header::clear_reset() {
  _impl_.reset_ = false;
}
inline bool Header::_internal_reset() const {
  return _impl_.reset_;
}
inline bool Header::reset() const {
  // @@protoc_insertion_point(field_get:Header.reset)
  return _internal_reset();
}
inline void Header::_internal_set_reset(bool value) {
  
  _impl_.reset_ = value;
}
inline void Header::set_reset(bool value) {
  _internal_set_reset(value);
  // @@protoc_insertion_point(field_set:Header.reset)
}

// -------------------------------------------------------------------

// Tensor

// .Tensor.DataType dtype = 1;
inline void Tensor::clear_dtype() {
  _impl_.dtype_ = 0;
}
inline ::Tensor_DataType Tensor::_internal_dtype() const {
  return static_cast< ::Tensor_DataType >(_impl_.dtype_);
}
inline ::Tensor_DataType Tensor::dtype() const {
  // @@protoc_insertion_point(field_get:Tensor.dtype)
  return _internal_dtype();
}
inline void Tensor::_internal_set_dtype(::Tensor_DataType value) {
  
  _impl_.dtype_ = value;
}
inline void Tensor::set_dtype(::Tensor_DataType value) {
  _internal_set_dtype(value);
  // @@protoc_insertion_point(field_set:Tensor.dtype)
}

// repeated int32 shape = 2;
inline int Tensor::_internal_shape_size() const {
  return _impl_.shape_.size();
}
inline int Tensor::shape_size() const {
  return _internal_shape_size();
}
inline void Tensor::clear_shape() {
  _impl_.shape_.Clear();
}
inline int32_t Tensor::_internal_shape(int index) const {
  return _impl_.shape_.Get(index);
}
inline int32_t Tensor::shape(int index) const {
  // @@protoc_insertion_point(field_get:Tensor.shape)
  return _internal_shape(index);
}
inline void Tensor::set_shape(int index, int32_t value) {
  _impl_.shape_.Set(index, value);
  // @@protoc_insertion_point(field_set:Tensor.shape)
}
inline void Tensor::_internal_add_shape(int32_t value) {
  _impl_.shape_.Add(value);
}
inline void Tensor::add_shape(int32_t value) {
  _internal_add_shape(value);
  // @@protoc_insertion_point(field_add:Tensor.shape)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Tensor::_internal_shape() const {
  return _impl_.shape_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Tensor::shape() const {
  // @@protoc_insertion_point(field_list:Tensor.shape)
  return _internal_shape();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Tensor::_internal_mutable_shape() {
  return &_impl_.shape_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Tensor::mutable_shape() {
  // @@protoc_insertion_point(field_mutable_list:Tensor.shape)
  return _internal_mutable_shape();
}

// bytes data = 3;
inline void Tensor::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& Tensor::data() const {
  // @@protoc_insertion_point(field_get:Tensor.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Tensor::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Tensor.data)
}
inline std::string* Tensor::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Tensor.data)
  return _s;
}
inline const std::string& Tensor::_internal_data() const {
  return _impl_.data_.Get();
}
inline void Tensor::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* Tensor::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* Tensor::release_data() {
  // @@protoc_insertion_point(field_release:Tensor.data)
  return _impl_.data_.Release();
}
inline void Tensor::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Tensor.data)
}

// -------------------------------------------------------------------

// MultiModalInput

// .Header header = 1;
inline bool MultiModalInput::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool MultiModalInput::has_header() const {
  return _internal_has_header();
}
inline void MultiModalInput::clear_header() {
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
}
inline const ::Header& MultiModalInput::_internal_header() const {
  const ::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::Header&>(
      ::_Header_default_instance_);
}
inline const ::Header& MultiModalInput::header() const {
  // @@protoc_insertion_point(field_get:MultiModalInput.header)
  return _internal_header();
}
inline void MultiModalInput::unsafe_arena_set_allocated_header(
    ::Header* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MultiModalInput.header)
}
inline ::Header* MultiModalInput::release_header() {
  
  ::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Header* MultiModalInput::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:MultiModalInput.header)
  
  ::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::Header* MultiModalInput::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::Header>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::Header* MultiModalInput::mutable_header() {
  ::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:MultiModalInput.header)
  return _msg;
}
inline void MultiModalInput::set_allocated_header(::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:MultiModalInput.header)
}

// repeated .Tensor images = 2;
inline int MultiModalInput::_internal_images_size() const {
  return _impl_.images_.size();
}
inline int MultiModalInput::images_size() const {
  return _internal_images_size();
}
inline void MultiModalInput::clear_images() {
  _impl_.images_.Clear();
}
inline ::Tensor* MultiModalInput::mutable_images(int index) {
  // @@protoc_insertion_point(field_mutable:MultiModalInput.images)
  return _impl_.images_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >*
MultiModalInput::mutable_images() {
  // @@protoc_insertion_point(field_mutable_list:MultiModalInput.images)
  return &_impl_.images_;
}
inline const ::Tensor& MultiModalInput::_internal_images(int index) const {
  return _impl_.images_.Get(index);
}
inline const ::Tensor& MultiModalInput::images(int index) const {
  // @@protoc_insertion_point(field_get:MultiModalInput.images)
  return _internal_images(index);
}
inline ::Tensor* MultiModalInput::_internal_add_images() {
  return _impl_.images_.Add();
}
inline ::Tensor* MultiModalInput::add_images() {
  ::Tensor* _add = _internal_add_images();
  // @@protoc_insertion_point(field_add:MultiModalInput.images)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >&
MultiModalInput::images() const {
  // @@protoc_insertion_point(field_list:MultiModalInput.images)
  return _impl_.images_;
}

// repeated .Tensor languages = 3;
inline int MultiModalInput::_internal_languages_size() const {
  return _impl_.languages_.size();
}
inline int MultiModalInput::languages_size() const {
  return _internal_languages_size();
}
inline void MultiModalInput::clear_languages() {
  _impl_.languages_.Clear();
}
inline ::Tensor* MultiModalInput::mutable_languages(int index) {
  // @@protoc_insertion_point(field_mutable:MultiModalInput.languages)
  return _impl_.languages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >*
MultiModalInput::mutable_languages() {
  // @@protoc_insertion_point(field_mutable_list:MultiModalInput.languages)
  return &_impl_.languages_;
}
inline const ::Tensor& MultiModalInput::_internal_languages(int index) const {
  return _impl_.languages_.Get(index);
}
inline const ::Tensor& MultiModalInput::languages(int index) const {
  // @@protoc_insertion_point(field_get:MultiModalInput.languages)
  return _internal_languages(index);
}
inline ::Tensor* MultiModalInput::_internal_add_languages() {
  return _impl_.languages_.Add();
}
inline ::Tensor* MultiModalInput::add_languages() {
  ::Tensor* _add = _internal_add_languages();
  // @@protoc_insertion_point(field_add:MultiModalInput.languages)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >&
MultiModalInput::languages() const {
  // @@protoc_insertion_point(field_list:MultiModalInput.languages)
  return _impl_.languages_;
}

// repeated .Tensor states = 4;
inline int MultiModalInput::_internal_states_size() const {
  return _impl_.states_.size();
}
inline int MultiModalInput::states_size() const {
  return _internal_states_size();
}
inline void MultiModalInput::clear_states() {
  _impl_.states_.Clear();
}
inline ::Tensor* MultiModalInput::mutable_states(int index) {
  // @@protoc_insertion_point(field_mutable:MultiModalInput.states)
  return _impl_.states_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >*
MultiModalInput::mutable_states() {
  // @@protoc_insertion_point(field_mutable_list:MultiModalInput.states)
  return &_impl_.states_;
}
inline const ::Tensor& MultiModalInput::_internal_states(int index) const {
  return _impl_.states_.Get(index);
}
inline const ::Tensor& MultiModalInput::states(int index) const {
  // @@protoc_insertion_point(field_get:MultiModalInput.states)
  return _internal_states(index);
}
inline ::Tensor* MultiModalInput::_internal_add_states() {
  return _impl_.states_.Add();
}
inline ::Tensor* MultiModalInput::add_states() {
  ::Tensor* _add = _internal_add_states();
  // @@protoc_insertion_point(field_add:MultiModalInput.states)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Tensor >&
MultiModalInput::states() const {
  // @@protoc_insertion_point(field_list:MultiModalInput.states)
  return _impl_.states_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Tensor_DataType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Tensor_DataType>() {
  return ::Tensor_DataType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
